### ISSUE TITLE
Issue with num-violations Reporting in PR Without Apex Code Changes

### ISSUE THREAD

**Issue by neozhu** [forcedotcom/run-code-analyzer#24] opened 2024-03-12 07:27 UTC
![image](https://github.com/forcedotcom/run-code-analyzer/assets/1549611/57f895b5-9b66-4c91-bad0-7fbe8ed86f5a)

I'm using forcedotcom/run-code-analyzer and encountered an issue in my devops center project. The action reports `num-violations: 41`, but my PR doesn't modify any Apex code. I'm unsure why these violations are reported or how to find details about them.

Questions:
1. Why are violations reported in PRs without Apex code changes?
2. How can I see what the 41 violations are?

Thanks for any help.

**Comment by RaviVaranasi** [comment] 2024-03-17 02:25
You can click on the `Summary` tab 

<img width="352" alt="Screenshot 2024-03-16 at 9 13 29 PM" src="https://github.com/forcedotcom/run-code-analyzer/assets/51507/d7a80fcb-ab2b-402f-bc21-8d098f1750cb">


<img width="1453" alt="Screenshot 2024-03-16 at 9 24 41 PM" src="https://github.com/forcedotcom/run-code-analyzer/assets/51507/14a21806-0ac1-4662-afaa-269231ee24dd">

**Comment by stephen-carter-at-sf** [comment] 2024-05-28 12:38
@neozhu This GitHub action will run on whatever target you specify. By default it will run on all the checked out files (not just your PR changes). To see the results, you'll find an artifact and a job summary on the Summary tab of the job. Likewise, the log will show the results underneath the "Running Salesforce Code Analyzer" step.

Since everything is working as designed, I'm closing this issue.

**Closed by stephen-carter-at-sf** 2024-05-28 12:38 UTC
